version: '2'
services:
    premiumstable-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/premiumStable/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=premiumStable
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
